name: first challenge

on: push

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: print date
      run: date

  job2:
    name: second job
    runs-on: macos-latest
    steps:
      - name: print date
      run: date

  job3:
    name: third job
    runs-on: windows-latest
    steps:
      - name: print date
      run: Get-Date

  job4:
    needs: [job1, job2, job3]
    name: fourth job
    runs-on: ubuntu-latest
    steps:
      - name: print date
      run: date