name: My First Github Action

on: push

jobs: 
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
     -  name: first step
        uses: actions/checkout@v2
     -  name: second job
        run: env | sort
  job2:
    needs: job1
    name: second job
    runs-on: windows-latest
    steps: 
      - name: first step in second job
        uses: actions/checkout@v2
      - name: second step in second job
        run: "Get-ChildItem env: | Sort-Object name"
